version: '3.7'
services:
    redis:
        image: redis:latest
        command: redis-server --port 6379
        container_name: redis
        hostname: redis_boot
        labels:
            - "name=redis"
            - "mode=standalone"
        ports:
            - 6379:6379
        restart: always
        volumes:
            - ./data/:/data